# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1153d49ca2d5848487b519244671b691390b9067a78f7c4e853101c9639af13284a0b4c5640e1ab2c2d2da17900ca4352c88691e3792f5e312bfdf29235530fc

test:
  secret_key_base: 96fb3feb32190dfdf7eaddfd06c16088a7cd9bf3ea041fbd289371bc6592f9ef2d71d92775bb0511bd84ec07099aea8663e5282842c5069ff8c65c0f57e93c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
